apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnvos
resources:
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: dobrodelen-front
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-front
    newTag: "latest"
