apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnvos
resources:
  - back/deployment.yaml
  - back/service.yaml
  - back/ingress.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: dobrodelen-back
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-back
    newTag: 'f3e9e703e6217c3d697b58e9276e7b60bd142f88'
  - name: dobrodelen-front
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-front
    newTag: 'f3e9e703e6217c3d697b58e9276e7b60bd142f88'
