apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnvos
resources:
  - back/deployment.yaml
  - back/service.yaml
  - back/ingress.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: dobrodelen-back
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-back
    newTag: 'e460464623dc0e048b7adf94ff975247656302bb'
  - name: dobrodelen-front
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-front
    newTag: 'e460464623dc0e048b7adf94ff975247656302bb'
