apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnvos
resources:
  - back/deployment.yaml
  - back/service.yaml
  - back/ingress.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: dobrodelen-back
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-back
    newTag: 'abc50b10e2085544d5ab6744f3cc7369c4e51b2b'
  - name: dobrodelen-front
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-front
    newTag: 'abc50b10e2085544d5ab6744f3cc7369c4e51b2b'
