apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnvos
resources:
  - back/deployment.yaml
  - back/service.yaml
  - back/ingress.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: dobrodelen-back
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-back
    newTag: 'fcefc2341a26f3a755d4ab113a2f88f79e08d634'
  - name: dobrodelen-front
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-front
    newTag: 'fcefc2341a26f3a755d4ab113a2f88f79e08d634'
