apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnvos
resources:
  - back/deployment.yaml
  - back/service.yaml
  - back/ingress.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: dobrodelen-back
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-back
    newTag: 'c1065a52a8fc23fc8760e63455ec906400b26f52'
  - name: dobrodelen-front
    newName: rg.fr-par.scw.cloud/djnd/dobrodelen-front
    newTag: 'c1065a52a8fc23fc8760e63455ec906400b26f52'
