version: '3'

volumes:
  postgres-data:


services:
  wagtail:
    build:
      context: ./back
      dockerfile: dev.Dockerfile
    working_dir: /app
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/app:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: dobrodelen.settings.k8s
      DJANGO_DEBUG: "true"
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_NAME: wagtail
      DJANGO_DATABASE_USER: wagtail
      DJANGO_DATABASE_PASSWORD: changeme
    depends_on:
      - db

  nuxt:
    build:
      context: ./front
      dockerfile: dev.Dockerfile
    working_dir: /nuxt_app
    command: yarn dev
    volumes:
      - ./front:/nuxt_app:delegated,rw
    ports:
      - "3000:3000"
      - "24678:24678" # dev server hot reload
    environment:
      - NUXT_UNLOCK_PASSWORD=unlockmepls
      - NUXT_PUBLIC_API_BASE_SERVER=http://wagtail:8000
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: wagtail
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
