# Generated by Django 2.2.3 on 2019-07-05 13:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0003_attachment_criterion_link_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_of_business_1', models.IntegerField(default=0, verbose_name='število sestankov nadzornega/upravnega odbora v zadnjem letu')),
                ('control_of_business_2', models.IntegerField(default=0, verbose_name='število neodvisnih članov nadzornega/upravnega odbora, ki ima glasovalno pravico')),
                ('control_of_business_3', models.IntegerField(default=0, verbose_name='odstotek neodvisnih članov z glasovalno pravico')),
                ('control_of_business_4', models.IntegerField(default=0, verbose_name='organizacija ima zapisnike sej')),
                ('strategic_planning_2_1', models.IntegerField(default=0, verbose_name='organizacija ima strateški načrt')),
                ('strategic_planning_2_2', models.IntegerField(default=0, verbose_name='organizacija spremlja doseganje strateškega načrta')),
                ('strategic_planning_2_3', models.IntegerField(default=0, verbose_name='organizacija pripravlja poročila o spremljanju napredka pri doseganju strateških ciljev')),
                ('financial_management_3_1', models.IntegerField(default=0, verbose_name='odstotek sredstev, ki jih porabi za izvedbo programa')),
                ('financial_management_3_2', models.IntegerField(default=0, verbose_name='odstotek sredstev, ki jh organizacija porabi za splošno delovanje')),
                ('financial_management_3_3', models.IntegerField(default=0, verbose_name='znesek, ki ga organizacija porabi na vsakih zbranih 100 €')),
                ('financial_management_3_4_1', models.IntegerField(default=0, verbose_name='viri sredstev')),
                ('financial_management_3_4_2', models.IntegerField(default=0, verbose_name='delež prihodkov iz navečjega posameznega vira')),
                ('financial_management_3_5_1', models.IntegerField(default=0, verbose_name='organizacija daje posojila povezanim osebam')),
                ('financial_management_3_5_2', models.IntegerField(default=0, verbose_name='organizacija prejema posojila od povezanih oseb')),
                ('financial_management_3_6', models.IntegerField(default=0, verbose_name='razmerje med najvišjo in povprečno plačo v organizaciji')),
                ('transparency_of_organizations_4_1', models.IntegerField(default=0, verbose_name='organizacija ima objavljena letna poročila o delu')),
                ('transparency_of_organizations_4_2', models.IntegerField(default=0, verbose_name='letna poročila o delu so razumljiva')),
                ('transparency_of_organizations_4_2_1', models.IntegerField(default=0, verbose_name='organizacija ima objavljena letna finančna poročila')),
                ('transparency_of_organizations_4_2_2', models.IntegerField(default=0, verbose_name='finančna poročila so razumljiva')),
                ('transparency_of_organizations_4_2_3', models.IntegerField(default=0, verbose_name='finančna poročila so razdeljena po programih in vrstah stroškov in prihodkov')),
                ('transparency_of_organizations_4_3', models.IntegerField(default=0, verbose_name='Objavljene so plače vodstva')),
                ('transparency_of_organizations_4_4', models.IntegerField(default=0, verbose_name='objavljeno je razmerje med plačami')),
                ('transparency_of_organizations_4_5', models.IntegerField(default=0, verbose_name='objavljen je seznam ključnih zaposlenih')),
                ('transparency_of_organizations_4_6', models.IntegerField(default=0, verbose_name='obljavljeni so člani nadzornega/upravnega odbora')),
                ('transparency_of_organizations_4_7', models.IntegerField(default=0, verbose_name='objavljen je finančni načrt za tekoče leto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizacija', 'verbose_name_plural': 'Organizacije'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='criterions',
        ),
        migrations.AddField(
            model_name='organization',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='link',
            name='organization',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.Organization'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Criterion',
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='organization',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.Organization'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='organization',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='home.Organization'),
        ),
    ]
