# Generated by Django 2.2.3 on 2019-07-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190705_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='stars',
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_1',
            field=models.IntegerField(default=0, verbose_name='1.1 - Število sestankov nadzornega/upravnega odbora v zadnjem letu'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_2',
            field=models.IntegerField(default=0, verbose_name='1.2 - Število neodvisnih članov nadzornega/upravnega odbora, ki ima glasovalno pravico'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_3',
            field=models.IntegerField(default=0, verbose_name='1.3 - Odstotek neodvisnih članov z glasovalno pravico'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_4',
            field=models.IntegerField(default=0, verbose_name='1.4 - Organizacija ima zapisnike sej'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_1',
            field=models.IntegerField(default=0, verbose_name='3.1 - Odstotek sredstev, ki jih porabi za izvedbo programa'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_2',
            field=models.IntegerField(default=0, verbose_name='3.2 - Odstotek sredstev, ki jh organizacija porabi za splošno delovanje'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_3',
            field=models.IntegerField(default=0, verbose_name='3.3 - Znesek, ki ga organizacija porabi na vsakih zbranih 100 €'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_1',
            field=models.IntegerField(default=0, verbose_name='3.4.1 - Viri sredstev'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_2',
            field=models.IntegerField(default=0, verbose_name='3.4.2 - Delež prihodkov iz navečjega posameznega vira'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_5_1',
            field=models.IntegerField(default=0, verbose_name='3.5.1 - Organizacija daje posojila povezanim osebam'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_5_2',
            field=models.IntegerField(default=0, verbose_name='3.5.2 - Organizacija prejema posojila od povezanih oseb'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_6',
            field=models.IntegerField(default=0, verbose_name='3.6 - Razmerje med najvišjo in povprečno plačo v organizaciji'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_1',
            field=models.IntegerField(default=0, verbose_name='2.1 - Organizacija ima strateški načrt'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_2',
            field=models.IntegerField(default=0, verbose_name='2.2 - Organizacija spremlja doseganje strateškega načrta'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_3',
            field=models.IntegerField(default=0, verbose_name='2.3 - Organizacija pripravlja poročila o spremljanju napredka pri doseganju strateških ciljev'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_1',
            field=models.IntegerField(default=0, verbose_name='4.1 - Organizacija ima objavljena letna poročila o delu'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2',
            field=models.IntegerField(default=0, verbose_name='4.2 - Letna poročila o delu so razumljiva'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_1',
            field=models.IntegerField(default=0, verbose_name='4.2.1 - Organizacija ima objavljena letna finančna poročila'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_2',
            field=models.IntegerField(default=0, verbose_name='4.2.2 - Finančna poročila so razumljiva'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_3',
            field=models.IntegerField(default=0, verbose_name='4.2.3 - Finančna poročila so razdeljena po programih in vrstah stroškov in prihodkov'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_3',
            field=models.IntegerField(default=0, verbose_name='4.3 - Objavljene so plače vodstva'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_4',
            field=models.IntegerField(default=0, verbose_name='4.4 - Objavljeno je razmerje med plačami'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_5',
            field=models.IntegerField(default=0, verbose_name='4.5 - Objavljen je seznam ključnih zaposlenih'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_6',
            field=models.IntegerField(default=0, verbose_name='4.6 - Obljavljeni so člani nadzornega/upravnega odbora'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_7',
            field=models.IntegerField(default=0, verbose_name='4.7 - Objavljen je finančni načrt za tekoče leto'),
        ),
    ]
