# Generated by Django 2.2.3 on 2019-07-09 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190708_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='signup_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
