# Generated by Django 2.2.3 on 2019-07-23 14:16

from django.db import migrations, models
import django.db.models.deletion
import home.models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_organization_signup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('meeting_dates', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, verbose_name='Ime in priimek')),
                ('role', models.CharField(default='', max_length=512, verbose_name='povezava z organizacijo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='additional_names',
            field=models.TextField(blank=True, default='', verbose_name='Druga imena, pod katerimi je organizacija poznana (kratice, okrajšave)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='audited_report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='revidirano poročilo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='avg_revenue',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='povprečni letni proračun v zadnjih treh letih'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_info',
            field=models.TextField(blank=True, default='', verbose_name='Kontakt: (ime in priimek, e-pošta, telefon)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='employed',
            field=models.IntegerField(blank=True, default=0, verbose_name='število zaposlenih v zadnjem zaključenem letu'),
        ),
        migrations.AddField(
            model_name='organization',
            name='finance_plan',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='finančni načrt za tekoče leto'),
        ),
        migrations.AddField(
            model_name='organization',
            name='finance_report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Finančno poročilo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='finance_report_ajpes',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='finančno poročilo, ki je bilo oddano na AJPES'),
        ),
        migrations.AddField(
            model_name='organization',
            name='given_loan',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='seznam danih posojil'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_public_interest',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija ima status delovanja v javnem interesu'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_charity',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija ima status humanitarne organizacije'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_voluntary',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija je vpisana v evidenco prostotovoljskih organizacij'),
        ),
        migrations.AddField(
            model_name='organization',
            name='milestiones_description',
            field=models.TextField(blank=True, default='', verbose_name='ali organizacija spremlja doseganje strateških ciljev? -> kratek opis kako, max 500 znakov'),
        ),
        migrations.AddField(
            model_name='organization',
            name='minutes_meeteng',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='priloga zapisnik zadnje seje'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mission',
            field=models.TextField(blank=True, default='', verbose_name='Poslanstvo organizacije (do 500 znakov)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_classes',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='akt o sistematizaciji delovnih mest in plačnih razredov'),
        ),
        migrations.AddField(
            model_name='organization',
            name='received_loans',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='seznam prejetih posojil'),
        ),
        migrations.AddField(
            model_name='organization',
            name='strategic_goals',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='pisna poročila o spremljanju stateških ciljev'),
        ),
        migrations.AddField(
            model_name='organization',
            name='strategic_planning',
            field=models.BooleanField(default=False, verbose_name='Ali organizacija strateško načrtuje?'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='davčna številka'),
        ),
        migrations.AddField(
            model_name='organization',
            name='wages_ratio',
            field=models.TextField(blank=True, default='', verbose_name='razmerje med najvišjo in povprečno plačo v organizaciji'),
        ),
        migrations.AddField(
            model_name='organization',
            name='web_page',
            field=models.URLField(blank=True, default='', max_length=512, verbose_name='spletna stran'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zero5',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija je na seznamu upravičencev do 0,5 % dohodnine'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='kratek opis organizacije (do 1500 znakov)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Uradno ime organizacije (iz AJPES)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='signup_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ali za svoje delo v odboru prejema nadomestilo')),
                ('board', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='home.Board')),
                ('member', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='home.Member')),
                ('organization', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='home.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='organization',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='home.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='area',
            field=models.ManyToManyField(blank=True, default='', related_name='organization', to='home.Area', verbose_name='Področje delovanja (lahko izberete več možnosti)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='board_members',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='organization_supervisor', through='home.BoardMember', to='home.Member'),
        ),
    ]
