# Generated by Django 2.2.3 on 2019-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190723_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_area',
            field=models.TextField(default='', verbose_name='Področje delovanja Other'),
        ),
    ]
