# Generated by Django 2.2.3 on 2019-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190821_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='minutes_meeteng',
            new_name='minutes_meeting',
        ),
        migrations.AddField(
            model_name='organization',
            name='has_minutes_meeting',
            field=models.BooleanField(default=False, verbose_name='ima priloga zapisnik zadnje seje?'),
        ),
    ]
