# Generated by Django 2.2.3 on 2019-08-22 09:13

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190821_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Povezava'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='audited_report',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Revidirano poročilo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avg_revenue',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Povprečni letni proračun v zadnjih treh letih'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=128, verbose_name='Kontakt: e-pošta'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='custom_area',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Področje delovanja: Drugo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Kratek opis organizacije (do 1500 znakov)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employed',
            field=models.IntegerField(blank=True, default=0, verbose_name='Število zaposlenih v zadnjem zaključenem letu'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='finance_plan',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Finančni načrt za tekoče leto'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='finance_report',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Finančno poročilo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='finance_report_ajpes',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Finančno poročilo, ki je bilo oddano na AJPES'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='given_loan',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Seznam danih posojil'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_audited_report',
            field=models.BooleanField(default=False, verbose_name='Ali je organizacija dolžna revidirati svoja finančna poročila?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_finance_plan',
            field=models.BooleanField(default=False, verbose_name='Ali ima organizacija finančni načrt za tekoče leto?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_given_loans',
            field=models.BooleanField(default=False, verbose_name='Ali organizacija daje posojila povezanim osebam?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_milestiones_description',
            field=models.BooleanField(default=False, verbose_name='Ali organizacija spremlja doseganje strateških ciljev?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_minutes_meeting',
            field=models.BooleanField(default=False, verbose_name='Ali organizacija vodi zapisnike sej?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_payment_classes',
            field=models.BooleanField(default=False, verbose_name='Ali ima organizacija akt o sistematizaciji delovnih mest in plačnih razredov?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_received_loans',
            field=models.BooleanField(default=False, verbose_name='Ali organizacija prejema posojila od povezanih oseb?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_strategic_goals',
            field=models.BooleanField(default=False, verbose_name='Ali organizacija vodi pisna poročila o spremljanju stateških ciljev?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='milestiones_description',
            field=models.TextField(blank=True, default='', verbose_name='Kratek opis kako organizacija spremlja doseganje strateških ciljev (do 500 znakov)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='minutes_meeting',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Zapisnik zadnje seje'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_classes',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Akt o sistematizaciji delovnih mest in plačnih razredov'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Je organizacija objavljena?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='received_loans',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Seznam prejetih posojil'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='signup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Čas končane prijave'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='strategic_goals',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Priloga: Pisna poročila o spremljanju stateških ciljev'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Davčna številka'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='wages_ratio',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Kakšno je razmerje med najvišjo in povprečno plačo v organizaciji?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='web_page',
            field=models.URLField(blank=True, default='', max_length=512, verbose_name='Spletna stran'),
        ),
        migrations.DeleteModel(
            name='DocumentAttachment',
        ),
    ]
