# Generated by Django 2.2.5 on 2019-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_organization_signup_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_published_board_members',
            field=models.BooleanField(default=False, verbose_name='Obljavljeni so člani nadzornega/upravnega odbora'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_published_employee_list',
            field=models.BooleanField(default=False, verbose_name='Objavljen je seznam ključnih zaposlenih'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_published_executive_salaries',
            field=models.BooleanField(default=False, verbose_name='Objavljene so plače vodstva'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_published_financial_plan',
            field=models.BooleanField(default=False, verbose_name='Objavljen je finančni načrt za tekoče leto'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_published_financial_reports',
            field=models.BooleanField(default=False, verbose_name='Organizacija ima objavljena letna finančna poročila'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_published_salary_ratio',
            field=models.BooleanField(default=False, verbose_name='Objavljeno je razmerje med plačami'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_published_work_reports',
            field=models.BooleanField(default=False, verbose_name='Organizacija ima objavljena letna poročila o delu'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published_board_members_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenega seznama članov odbora'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published_employee_list_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenega seznama ključnih zaposlenih'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published_executive_salaries_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenih plač vodstva'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published_financial_plan_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenega finančnega načrta za tekoče leto'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published_financial_reports_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenih finančnih poročil'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published_salary_ratio_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenih razmerij med plačami'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published_work_reports_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenih letnih poročil o delu'),
        ),
    ]
