# Generated by Django 2.2.5 on 2019-09-23 11:57

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190923_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='board_members',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='custom_role',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Povezava z organizacijo: Drugo'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='Ime in priimek'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Član'), ('2', 'Predstavnik uporabnikov'), ('3', 'Predstavnik zaposlenih'), ('4', 'Predstavnik ustanoviteljev'), ('5', 'Imenovan na podlagi sorodstvenih/prijateljskih vezi'), ('6', 'Neodvisni predstavnik'), ('7', 'Drugo:')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='council_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Datumi srečanj v preteklem letu (svet zavoda)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='council_members',
            field=modelcluster.fields.ParentalManyToManyField(related_name='organization_council', to='home.BoardMember'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_council',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija ima svet zavoda, ki se je v preteklem letu srečal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_management_board',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija ima upravni odbor, ki se je v preteklem letu srečal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_other_board',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija ima drug organ, ki se je v preteklem letu srečal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_supervisory_board',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organizacija ima nadzorni odbor, ki se je v preteklem letu srečal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='management_board_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Datumi srečanj v preteklem letu (upravni odbor)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='management_board_members',
            field=modelcluster.fields.ParentalManyToManyField(related_name='organization_management_board', to='home.BoardMember'),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_board_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Datumi srečanj v preteklem letu (drug organ)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_board_members',
            field=modelcluster.fields.ParentalManyToManyField(related_name='organization_other_board', to='home.BoardMember'),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_board_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Ime organa'),
        ),
        migrations.AddField(
            model_name='organization',
            name='supervisory_board_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Datumi srečanj v preteklem letu (nadzorni odbor)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='supervisory_board_members',
            field=modelcluster.fields.ParentalManyToManyField(related_name='organization_supervisory_board', to='home.BoardMember'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
