# Generated by Django 2.2.5 on 2020-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20191001_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_1',
            field=models.IntegerField(default=0, help_text='Število sestankov | 5+ = 𝟓 | 4 = 𝟒 | 3 = 𝟑 | 2 = 𝟐 | 1 = 𝟏 | 0 = 𝟎 |', verbose_name='1.1 - Število sestankov nadzornega/upravnega odbora v zadnjem letu'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_2',
            field=models.IntegerField(default=0, help_text='Število članov | 5+ = 𝟑 | 3-5 = 𝟐 | 1-2 = 𝟏 | 0 = 𝟎 |', verbose_name='1.2 - Število neodvisnih članov nadzornega/upravnega odbora, ki ima glasovalno pravico'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_3',
            field=models.IntegerField(default=0, help_text='Odstotek neodvisnih članov | 75+ = 𝟑 | 50-75 = 𝟐 | <50 = 𝟏 | 0 = 𝟎 |', verbose_name='1.3 - Odstotek neodvisnih članov z glasovalno pravico'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_4',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='1.4 - Organizacija vodi zapisnike sej'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_1',
            field=models.IntegerField(default=0, help_text='Odstotek sredstev | 90+ = 𝟓 | 90-86 = 𝟒 | 85-76 = 𝟑 | 75-70 = 𝟐 | <70 = 𝟏 |', verbose_name='3.1 - Odstotek sredstev, ki jih porabi za izvedbo programa'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_2',
            field=models.IntegerField(default=0, help_text='Odstotek sredstev | <10 = 𝟓 | 10-14 = 𝟒 | 15-24 = 𝟑 | 25-30 = 𝟐 | 30+ = 𝟏 |', verbose_name='3.2 - Odstotek sredstev, ki jh organizacija porabi za splošno delovanje'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_3',
            field=models.IntegerField(default=0, help_text='Znesek | 0-5 = 𝟓 | 6-15 = 𝟒 | 16-24 = 𝟑 | 25-30 = 𝟐 | 30+ = 𝟏 |', verbose_name='3.3 - Znesek, ki ga organizacija porabi na vsakih zbranih 100 €'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_1',
            field=models.IntegerField(default=0, help_text='Število virov | 10+ = 𝟓 | 8- 9 = 𝟒 | 6-7 = 𝟑 | 3-5 = 𝟐 | <3 = 𝟏 |', verbose_name='3.4.1 - Viri sredstev'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_2',
            field=models.IntegerField(default=0, help_text='Odstotek prihodkov | <=20 = 𝟓 | 21-30 = 𝟒 | 31-40 = 𝟑 | 41-50 = 𝟐 | 50+ = 𝟏 |', verbose_name='3.4.2 - Delež prihodkov iz navečjega posameznega vira'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_5_1',
            field=models.IntegerField(default=0, help_text='Organizacija daje posojila povezanim osebam | Da = 𝟎 | Ne = 𝟒 |', verbose_name='3.5.1 - Organizacija daje posojila povezanim osebam'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_5_2',
            field=models.IntegerField(default=0, help_text='Organizacija prejema posojila od povezanih oseb | Da = 𝟎 | Ne = 𝟐 |', verbose_name='3.5.2 - Organizacija prejema posojila od povezanih oseb'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_6',
            field=models.IntegerField(default=0, help_text='Razmerje | <1:2 = 𝟓 | 1:2,9-1:2 = 𝟒 | 1:3,9-1:3 = 𝟑 | 1:4-1:5 = 𝟐 | >1:5 = 𝟏 |', verbose_name='3.6 - Razmerje med najvišjo in povprečno plačo v organizaciji'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_1',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='2.1 - Organizacija ima strateški načrt'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_2',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='2.2 - Organizacija spremlja doseganje strateškega načrta'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_3',
            field=models.IntegerField(default=0, help_text='| Da = 𝟏 | Ne = 𝟎 |', verbose_name='2.3 - Organizacija pripravlja poročila o spremljanju napredka pri doseganju strateških ciljev'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_1',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.1.1 - Organizacija ima objavljena letna poročila o delu'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.1.2 - Letna poročila o delu so razumljiva'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_1',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.2.1 - Organizacija ima objavljena letna finančna poročila'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_2',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.2.2 - Finančna poročila so razumljiva'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_3',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.2.3 - Finančna poročila so razdeljena po programih in vrstah stroškov in prihodkov'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_3',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.3 - Objavljene so plače vodstva'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_4',
            field=models.IntegerField(default=0, help_text='| Da = 𝟏 | Ne = 𝟎 |', verbose_name='4.4 - Objavljeno je razmerje med plačami'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_5',
            field=models.IntegerField(default=0, help_text='| Da = 𝟏 | Ne = 𝟎 |', verbose_name='4.5 - Objavljen je seznam ključnih zaposlenih'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_6',
            field=models.IntegerField(default=0, help_text='| Da = 𝟏 | Ne = 𝟎 |', verbose_name='4.6 - Obljavljeni so člani nadzornega/upravnega odbora'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_7',
            field=models.IntegerField(default=0, help_text='| Da = 𝟏 | Ne = 𝟎 |', verbose_name='4.7 - Objavljen je finančni načrt za tekoče leto'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_8',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.8 - Informacije so dostopne'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avg_revenue',
            field=models.IntegerField(blank=True, default=0, verbose_name='Povprečni letni proračun v zadnjih treh letih'),
        ),
    ]
