# Generated by Django 2.2.5 on 2020-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200129_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='transparency_of_organizations_4_8',
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_3',
            field=models.IntegerField(default=0, help_text='| Da = 𝟐 | Ne = 𝟎 |', verbose_name='4.3 - Objavljeni so prejemki vodstva'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_audited_report',
            field=models.BooleanField(default=False, verbose_name='Ali ima organizacija revidirana finančna poročila?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_executive_salaries',
            field=models.BooleanField(default=False, verbose_name='Objavljeni so prejemki vodstva'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_executive_salaries_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL do objavljenih prejemkov vodstva'),
        ),
    ]
