# Generated by Django 2.2.5 on 2021-09-29 13:08

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200131_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='financial_management_3_5_1',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='financial_management_3_5_2',
        ),
        migrations.AddField(
            model_name='criteria',
            name='control_of_business_5',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='1.5 - Организацијата има родова еднаквост во управниот орган'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='strategic_planning_2_4',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='2.4 - Организацијата подготвува годишен план'),
        ),
        migrations.AlterField(
            model_name='councilboardmember',
            name='custom_role',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Role in organization: Other'),
        ),
        migrations.AlterField(
            model_name='councilboardmember',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Receives compensation for his work on the board'),
        ),
        migrations.AlterField(
            model_name='councilboardmember',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='councilboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Član'), ('2', 'Predstavnik uporabnikov'), ('3', 'Predstavnik zaposlenih'), ('4', 'Predstavnik ustanoviteljev'), ('5', 'Imenovan na podlagi sorodstvenih/prijateljskih vezi'), ('6', 'Neodvisni predstavnik'), ('7', 'Drugo:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_1',
            field=models.IntegerField(default=0, help_text='Број на состаноци | 5+ = 𝟓 | 4 = 𝟒 | 3 = 𝟑 | 2 = 𝟐 | 1 = 𝟏 | 0 = 𝟎 |', verbose_name='1.1 - Број на состаноци на не-извршниот орган'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_2',
            field=models.IntegerField(default=0, help_text='Број на членови | 5+ = 𝟑 | 3-5 = 𝟐 | 1-2 = 𝟏 | 0 = 𝟎 |', verbose_name='1.2 - Број на независни членови со право на глас во не-извршниот орган'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_3',
            field=models.IntegerField(default=0, help_text='Процент на независни членови | 75+ = 𝟑 | 50-75 = 𝟐 | <50 = 𝟏 | 0 = 𝟎 |', verbose_name='1.3 - Процент на независни членови со право на глас'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='control_of_business_4',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='1.4 - Организацијата води записници од одржаните состаноци'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_1',
            field=models.IntegerField(default=0, help_text='Процент на средства | 90+ = 𝟓 | 90-86 = 𝟒 | 85-76 = 𝟑 | 75-70 = 𝟐 | <70 = 𝟏 |', verbose_name='3.1 - Процент од средствата употребени за спроведување на директни проектни активности'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_2',
            field=models.IntegerField(default=0, help_text='Процент од средствата | <10 = 𝟓 | 10-14 = 𝟒 | 15-24 = 𝟑 | 25-30 = 𝟐 | 30+ = 𝟏 |', verbose_name='3.2 - Процент на средства за тековно/оперативно работење'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_1',
            field=models.IntegerField(default=0, help_text='Број на извори | 10+ = 𝟓 | 8-9 = 𝟒 | 6-7 = 𝟑 | 3-5 = 𝟐 | <3 = 𝟏 |', verbose_name='3.4.1 - Извори на финансирање'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_2',
            field=models.IntegerField(default=0, help_text='Процент од приходи | <=20 = 𝟓 | 21-30 = 𝟒 | 31-40 = 𝟑 | 41-50 = 𝟐 | 50+ = 𝟏 |', verbose_name='3.4.2 - Удел на приходите од најголемиот извор'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_6',
            field=models.IntegerField(default=0, help_text='Сооднос | <1:2 = 𝟓 | 1:2,9-1:2 = 𝟒 | 1:3,9-1:3 = 𝟑 | 1:4-1:5 = 𝟐 | >1:5 = 𝟏 |', verbose_name='3.6 - Соодносот помеѓу највисоката и просечната плата во организацијата'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_1',
            field=models.IntegerField(default=0, help_text='| Да = 𝟑 | не = 𝟎 |', verbose_name='2.1 - Организацијата има стратешки (или годишен) план'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_2',
            field=models.IntegerField(default=0, help_text='| Да = 𝟑 | не = 𝟎 |', verbose_name='2.2 - Организацијата го мониторира (има рамка за мониторирање и презентира внатрешно прогрес) исполнувањето на стратешкиот план'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='strategic_planning_2_3',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='2.3 - Организацијата подготвува извештаи од мониторирање на исполнувањето стратешките цели'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_1',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.1.1 - Организацијата има објавени наративни годишни извештаи'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.1.2 - Наративните годишни извештаи се разбирливи'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_1',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.2.1 - Организацијата има објавени годишни финансиски извештаи'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_2',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.2.2 - Финансиските документи се разбирливи'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_2_3',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.2.3 - Финансиските документи се поделени по програми и видови на трошоци и приходи'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_3',
            field=models.IntegerField(default=0, help_text='| Да = 𝟏 | не = 𝟎 |', verbose_name='4.3 - Објавен е надоместокот кој го добива раководството'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_4',
            field=models.IntegerField(default=0, help_text='| Да = 𝟏 | не = 𝟎 |', verbose_name='4.4 - Објавен е соодносот на платите'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_5',
            field=models.IntegerField(default=0, help_text='| Да = 𝟏 | не = 𝟎 |', verbose_name='4.5 - Објавена е листа со клучните вработени лица'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_6',
            field=models.IntegerField(default=0, help_text='| Да = 𝟏 | не = 𝟎 |', verbose_name='4.6 - Објавени се членовите на не-извршните органи'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_7',
            field=models.IntegerField(default=0, help_text='| Да = 𝟏 | не = 𝟎 |', verbose_name='4.7 - Објавен е финансискиот план за тековната година'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='managementboardmember',
            name='custom_role',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Role in organization: Other'),
        ),
        migrations.AlterField(
            model_name='managementboardmember',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Receives compensation for his work on the board'),
        ),
        migrations.AlterField(
            model_name='managementboardmember',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='managementboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Član'), ('2', 'Predstavnik uporabnikov'), ('3', 'Predstavnik zaposlenih'), ('4', 'Predstavnik ustanoviteljev'), ('5', 'Imenovan na podlagi sorodstvenih/prijateljskih vezi'), ('6', 'Neodvisni predstavnik'), ('7', 'Drugo:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='additional_names',
            field=models.TextField(blank=True, default='', verbose_name='Other organization names (short names, acronyms, etc.)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.ManyToManyField(blank=True, default='', related_name='organization', to='home.Area', verbose_name='Area of operation (can select multiple)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='audited_report',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: Audited financial report'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avg_revenue',
            field=models.IntegerField(blank=True, default=0, verbose_name='Average annual budget for the last three years'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=128, verbose_name='Contact person: email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Contact person: name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Contact person: phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='council_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Dates of meetings in the previous year (council)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='custom_area',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Area of operation: Other'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Short description of organization (max. 1500 characters)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employed',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of employees in the last completed year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='finance_plan',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: Financial plan for the current year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='finance_report',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: Financial report'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='finance_report_ajpes',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: Financial report, submitted to public legal record agency'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='given_loan',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: List of provided loans'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_audited_report',
            field=models.BooleanField(default=False, verbose_name='Does the organization have audited financial reports?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_council',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organization has a council that met last year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_finance_plan',
            field=models.BooleanField(default=False, verbose_name='Does the organization have a financial plan for the current year?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_given_loans',
            field=models.BooleanField(default=False, verbose_name='Does the organization provide loans to related parties?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_management_board',
            field=models.BooleanField(blank=True, default=False, verbose_name='The organization has a management board that met last year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_milestiones_description',
            field=models.BooleanField(default=False, verbose_name='Does the organization monitor the achievement of strategic objectives?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_minutes_meeting',
            field=models.BooleanField(default=False, verbose_name='Does the organization keep minutes of meetings?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_other_board',
            field=models.BooleanField(blank=True, default=False, verbose_name='The organization has another body that has met in the past year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_payment_classes',
            field=models.BooleanField(default=False, verbose_name='Does the organization have an act on the systematization of jobs and pay grades?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_public_interest',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organization has the status of acting in the public interest'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_board_members',
            field=models.BooleanField(default=False, verbose_name='Organization has published a list of board members'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_employee_list',
            field=models.BooleanField(default=False, verbose_name='Organization has published a list of key employees'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_executive_salaries',
            field=models.BooleanField(default=False, verbose_name='Organization has published management remuneration'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_financial_plan',
            field=models.BooleanField(default=False, verbose_name='Organization has published the financial plan for the current year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_financial_reports',
            field=models.BooleanField(default=False, verbose_name='Organization has published annual financial reports'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_salary_ratio',
            field=models.BooleanField(default=False, verbose_name='Organization has published wage ratios'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_published_work_reports',
            field=models.BooleanField(default=False, verbose_name='Organization has published annual activity reports'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_received_loans',
            field=models.BooleanField(default=False, verbose_name='Does the organization receive loans from related parties?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_strategic_goals',
            field=models.BooleanField(default=False, verbose_name='Does the organization keep written reports on the monitoring of strategic objectives?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_supervisory_board',
            field=models.BooleanField(blank=True, default=False, verbose_name='The organization has a supervisory board that met last year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_charity',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organization has the status of a humanitarian organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Signup complete?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_voluntary',
            field=models.BooleanField(blank=True, default=False, verbose_name='Organization is entered in the register of voluntary organizations'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='management_board_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Dates of meetings in the previous year (management board)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='milestiones_description',
            field=models.TextField(blank=True, default='', verbose_name='Brief description of how the organization monitors the achievement of strategic objectives (max. 500 characters)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='minutes_meeting',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: Minutes of last meetings'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mission',
            field=models.TextField(blank=True, default='', verbose_name='Organization mission statement (max. 500 characters)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Legal organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='other_board_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Dates of meetings in the previous year (other body)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='other_board_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Name of other body'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_classes',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: Act on the systematization of jobs and pay grades'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_board_members_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL to the published list of board members'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_employee_list_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL to the published list of key employees'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_executive_salaries_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL to published management remuneration'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_financial_plan_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL to the published financial plan for the current year'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_financial_reports_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL to published annual financial reports'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_salary_ratio_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL to published wage ratios'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published_work_reports_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL to published annual activity reports'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='received_loans',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: List of received loans'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.ManyToManyField(blank=True, default='', related_name='organization', to='home.Region', verbose_name='Region (can select multiple)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='signup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signup finished time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='signup_time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signup started time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='strategic_goals',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_intance_path, verbose_name='Attachment: Written reports on the monitoring of strategic objectives'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='strategic_planning',
            field=models.BooleanField(default=False, verbose_name='Does the organization do strategic planning?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='supervisory_board_dates',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Dates of meetings in the previous year (supervisory board)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Tax number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='wages_ratio',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='What is the ratio between the highest and average wage in an organization?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='web_page',
            field=models.URLField(blank=True, default='', max_length=512, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='otherboardmember',
            name='custom_role',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Role in organization: Other'),
        ),
        migrations.AlterField(
            model_name='otherboardmember',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Receives compensation for his work on the board'),
        ),
        migrations.AlterField(
            model_name='otherboardmember',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='otherboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Član'), ('2', 'Predstavnik uporabnikov'), ('3', 'Predstavnik zaposlenih'), ('4', 'Predstavnik ustanoviteljev'), ('5', 'Imenovan na podlagi sorodstvenih/prijateljskih vezi'), ('6', 'Neodvisni predstavnik'), ('7', 'Drugo:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
        migrations.AlterField(
            model_name='supervisoryboardmember',
            name='custom_role',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Role in organization: Other'),
        ),
        migrations.AlterField(
            model_name='supervisoryboardmember',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Receives compensation for his work on the board'),
        ),
        migrations.AlterField(
            model_name='supervisoryboardmember',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='supervisoryboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Član'), ('2', 'Predstavnik uporabnikov'), ('3', 'Predstavnik zaposlenih'), ('4', 'Predstavnik ustanoviteljev'), ('5', 'Imenovan na podlagi sorodstvenih/prijateljskih vezi'), ('6', 'Neodvisni predstavnik'), ('7', 'Drugo:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
    ]
