# Generated by Django 2.2.5 on 2021-12-13 13:30

from django.db import migrations, models


def compute_points(criteria):
    fields = [
        f.name
        for f in criteria.__class__._meta.fields
        if f.name not in ["id", "organization", "stars", "points"]
    ]
    return sum(list(map(lambda f: getattr(criteria, f, 0), fields)))


def compute_stars(criteria):
    points = compute_points(criteria)
    if points < 30:
        return 0
    if points < 35:
        return 1
    if points < 41:
        return 2
    if points < 51:
        return 3
    if points < 61:
        return 4
    return 5


def recompute_points_and_stars(apps, schema_editor):
    Criteria = apps.get_model("home", "Criteria")
    db_alias = schema_editor.connection.alias
    for criteria in Criteria.objects.using(db_alias).all():
        criteria.points = compute_points(criteria)
        criteria.stars = compute_stars(criteria)
        criteria.save()


class Migration(migrations.Migration):

    dependencies = [("home", "0029_auto_20211116_1718")]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="points",
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.RunPython(recompute_points_and_stars, migrations.RunPython.noop),
    ]
