# Generated by Django 2.2.5 on 2021-09-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210929_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='financial_management_3_3',
        ),
        migrations.AlterField(
            model_name='councilboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Член'), ('2', 'Претставник на корисниците'), ('3', 'Претставник на вработените'), ('4', 'Претставник на основачите'), ('5', 'Именуван врз основа на роднински/пријателски врски'), ('6', 'Независен претставник'), ('7', 'Друго:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_1',
            field=models.IntegerField(default=0, help_text='Број на извори | 10+ = 𝟓 | 8-9 = 𝟒 | 6-7 = 𝟑 | 3-5 = 𝟐 | <3 = 𝟏 |', verbose_name='3.3.1 - Извори на финансирање'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_4_2',
            field=models.IntegerField(default=0, help_text='Процент од приходи | <=20 = 𝟓 | 21-30 = 𝟒 | 31-40 = 𝟑 | 41-50 = 𝟐 | 50+ = 𝟏 |', verbose_name='3.3.2 - Удел на приходите од најголемиот извор'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='financial_management_3_6',
            field=models.IntegerField(default=0, help_text='Сооднос | <1:2 = 𝟓 | 1:2,9-1:2 = 𝟒 | 1:3,9-1:3 = 𝟑 | 1:4-1:5 = 𝟐 | >1:5 = 𝟏 |', verbose_name='3.4 - Соодносот помеѓу највисоката и просечната плата во организацијата'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_3',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.3 - Објавен е надоместокот кој го добива раководството'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_4',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.4 - Објавен е соодносот на платите'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_5',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.5 - Објавена е листа со клучните вработени лица'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_6',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.6 - Објавени се членовите на не-извршните органи'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='transparency_of_organizations_4_7',
            field=models.IntegerField(default=0, help_text='| Да = 𝟐 | не = 𝟎 |', verbose_name='4.7 - Објавен е финансискиот план за тековната година'),
        ),
        migrations.AlterField(
            model_name='managementboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Член'), ('2', 'Претставник на корисниците'), ('3', 'Претставник на вработените'), ('4', 'Претставник на основачите'), ('5', 'Именуван врз основа на роднински/пријателски врски'), ('6', 'Независен претставник'), ('7', 'Друго:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
        migrations.AlterField(
            model_name='otherboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Член'), ('2', 'Претставник на корисниците'), ('3', 'Претставник на вработените'), ('4', 'Претставник на основачите'), ('5', 'Именуван врз основа на роднински/пријателски врски'), ('6', 'Независен претставник'), ('7', 'Друго:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
        migrations.AlterField(
            model_name='supervisoryboardmember',
            name='role',
            field=models.CharField(choices=[('1', 'Член'), ('2', 'Претставник на корисниците'), ('3', 'Претставник на вработените'), ('4', 'Претставник на основачите'), ('5', 'Именуван врз основа на роднински/пријателски врски'), ('6', 'Независен претставник'), ('7', 'Друго:')], default='1', max_length=2, verbose_name='Role in organization'),
        ),
    ]
