# Generated by Django 4.1.5 on 2023-01-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_auto_20230123_1636"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Criteria",
        ),
    ]
