# Generated by Django 4.1.5 on 2023-01-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_remove_organization_audited_report_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managementboardmember",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="otherboardmember",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="supervisoryboardmember",
            name="organization",
        ),
        migrations.DeleteModel(
            name="CouncilBoardMember",
        ),
        migrations.DeleteModel(
            name="ManagementBoardMember",
        ),
        migrations.DeleteModel(
            name="OtherBoardMember",
        ),
        migrations.DeleteModel(
            name="SupervisoryBoardMember",
        ),
    ]
