# Generated by Django 4.1.5 on 2023-01-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_remove_managementboardmember_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Datum pregleda"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="review_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Opombe ocenjevalca (ni javno)"
            ),
        ),
    ]
