# Generated by Django 4.1.9 on 2023-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_organization_review_date_organization_review_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="avg_revenue",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="description",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="donation_url",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="employed",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="has_public_interest",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_charity",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_voluntary",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="zero5",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="zero5_amount",
        ),
        migrations.AddField(
            model_name="organization",
            name="board_member_list_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 4: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="complaints_contact_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 6: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="complaints_process_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 7: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_information_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 5: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="financial_report_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 1: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="fundraising_report_with_purposes_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 2: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="fundraising_reports_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 1: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_board_member_list",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 4: Organizacija ima objavljen seznam članov nadzornih organov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_complaints_contact",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 6: Objavljene so informacije o možnosti pritožbe nad delom organizacije s podatki komu/kako poslati pritožbe",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_complaints_process",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 7: Objavljen je celoten pritožbeni postopek",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_contact_information",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 5: Objavljen je način, kako lahko posameznik stopi v stik z organizacijo",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_financial_report",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 1: Organizacija ima objavljeno letno finančno poročilo za preteklo leto",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_fundraising_report_with_purposes",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 2: Poročilo o zbranih sredstvih je razdeljeno po namenih zbiranja (fundraising akcijah)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_fundraising_reports",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 1: Objavljena so poročila o zbranih sredstvih",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_key_documents",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 1: Organizacija ima objavljene ključne dokumente (akt o ustanovitvi in/ali statut)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_key_employee_list",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 3: Organizacija ima objavljen seznam ključnih zaposlenih",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_main_sources_of_financing",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 4: Objavljeni so glavni viri financiranja (prihodki)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_management_revenues",
            field=models.BooleanField(
                default=False, verbose_name="Kriterij 5: Objavljeni so prihodki vodstva"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_mission",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 2: Organizacija ima objavljeno poslanstvo",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_operating_expenses",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 3: Objavljen je podatek o višini ali odstotku sredstev, ki ga organizacija nameni za delovanje (hladni pogon)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_report_about_work",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 2: Objavljeno je vsebinsko poročilo, iz katerega je jasno razvidno, s čim se organizacija ukvarja",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_report_with_results",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 3: Vsebinsko poročilo vključuje tudi rezultate (dosežke, učinke), ne zgolj aktivnosti",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_salary_ratio",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 6: Objavljeno je razmerje med najnižjo, povprečno in najvišjo plačo",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_strategic_objectives",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 5: Organizacija ima objavljene glavne strateške cilje",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_substantive_report",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 1: Objavljeno je vsebinsko poročilo za preteklo leto",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_understandable_financial_report",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 2: Finančna poročila so razdeljena po vrstah stroškov, ki so razumljiva javnosti (npr. stroški zaposlenih, potni stroški, stroški za zunanje izvajalce, itd.)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_published_work_plan",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 4: Organizacija ima objavljen načrt dela za tekoče leto",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="key_documents_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 1: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="key_employee_list_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 3: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="main_sources_of_financing_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 4: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="management_revenues_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 5: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="mission_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 2: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="operating_expenses_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 3: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_about_work_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 2: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_with_results_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 3: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="salary_ratio_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 6: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="strategic_objectives_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 5: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="substantive_report_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 1: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="understandable_financial_report_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 2: URL do objavljenega dokumenta/podatkov",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_accessibility_contrast",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 1: Barvni kontrast med tekstom in ozadjem spletne strani je vsaj 4.5:1",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_accessibility_disabilities",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 3: Spletna stran je dostopna osebam z motoričnimi ali kognitivnimi ovirami",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_accessibility_zoom",
            field=models.BooleanField(
                default=False,
                verbose_name="Kriterij 2: Spletno mesto je berljivo tudi ob povečavi na 200 %",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="work_plan_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Kriterij 4: URL do objavljenega dokumenta/podatkov",
            ),
        ),
    ]
