# Generated by Django 4.1.5 on 2023-07-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_remove_organization_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="account_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Številka tekočega računa",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="donation_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Povezava na spletno stran organizacije, kjer je možno donirati sredstva (če obstaja)",
            ),
        ),
    ]
