# Generated by Django 4.1.5 on 2023-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_organization_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="board_member_list_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 4: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="complaints_contact_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 6: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="complaints_process_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 7: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_information_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 5: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="financial_report_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 1: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="fundraising_report_with_purposes_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 2: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="fundraising_reports_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 1: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="key_documents_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 1: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="key_employee_list_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 3: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="main_sources_of_financing_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 4: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="management_revenues_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 5: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="mission_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 2: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="operating_expenses_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 3: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_about_work_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 2: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_with_results_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 3: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="salary_ratio_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 6: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="strategic_objectives_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 5: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="substantive_report_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 1: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="understandable_financial_report_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 2: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_accessibility_contrast_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 1: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_accessibility_disabilities_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 3: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_accessibility_zoom_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 2: Opombe ocenjevalca (ni javno)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="work_plan_notes",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Kriterij 4: Opombe ocenjevalca (ni javno)",
            ),
        ),
    ]
