apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobrodelen-front
  labels:
    app: dobrodelen-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dobrodelen-front
  template:
    metadata:
      labels:
        app: dobrodelen-front
    spec:
      containers:
        - name: dobrodelen-front
          image: dobrodelen-front
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_PUBLIC_API_BASE_SERVER
              value: https://api.dobrodelen.si
            - name: NUXT_PUBLIC_API_BASE
              value: https://api.dobrodelen.si
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 50m
